import React, { useState, useEffect } from 'react';
import { Market, HistoricalResult, CandidatePrediction } from '../types';
import { generatePredictions, MODEL_VERSION } from '../lib/predictionEngine';
import {
  Sparkles,
  Calendar,
  ShieldAlert,
  Bot,
  RefreshCw,
  Clock,
  ArrowLeft,
  ChevronDown,
  Info,
  CheckCircle2,
  AlertTriangle,
  Flame,
  Layers,
  Target,
  ShieldCheck
} from 'lucide-react';

interface PredictionDetailPageProps {
  market: Market;
  history: HistoricalResult[];
  onBack: () => void;
  onNavigateChart: (marketSlug: string) => void;
}

export const PredictionDetailPage: React.FC<PredictionDetailPageProps> = ({
  market,
  history,
  onBack,
  onNavigateChart
}) => {
  const todayStr = '2026-09-17';
  const tomorrowStr = '2026-09-18';

  const [dateMode, setDateMode] = useState<'today' | 'tomorrow' | 'custom'>('today');
  const [customDate, setCustomDate] = useState<string>(todayStr);
  const [panaFilterCount, setPanaFilterCount] = useState<5 | 10 | 20>(10);

  // AI explanation state
  const [aiExplanation, setAiExplanation] = useState<string>('');
  const [isAiLoading, setIsAiLoading] = useState<boolean>(false);
  const [aiSource, setAiSource] = useState<string>('');

  const targetDate =
    dateMode === 'today' ? todayStr : dateMode === 'tomorrow' ? tomorrowStr : customDate;

  // Run statistical engine
  const { singles, jodis, panas, otc, trainingDataCount } = generatePredictions(history, targetDate);

  const displayedPanas = panas.slice(0, panaFilterCount);

  // Trigger AI explanation
  const fetchAiExplanation = async () => {
    setIsAiLoading(true);
    try {
      const response = await fetch('/api/ai/explain', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          marketName: market.name,
          predictionDate: targetDate,
          topSingles: singles.slice(0, 3),
          topJodis: jodis.slice(0, 3),
          topPanas: displayedPanas.slice(0, 3),
          otc,
          trainingDataCount,
          modelVersion: MODEL_VERSION
        })
      });
      const data = await response.json();
      setAiExplanation(data.explanation || 'Statistical summary ready.');
      setAiSource(data.source || 'engine');
    } catch (err) {
      console.error('AI Explanation error:', err);
      setAiExplanation('Statistical factor analysis generated by local engine.');
    } finally {
      setIsAiLoading(false);
    }
  };

  // Auto-fetch explanation when market or date changes
  useEffect(() => {
    if (trainingDataCount >= 3) {
      fetchAiExplanation();
    }
  }, [market.id, targetDate]);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Navigation & Header */}
      <div>
        <button
          id="btn-back-to-predictions"
          onClick={onBack}
          className="inline-flex items-center gap-1.5 text-xs font-mono text-slate-400 hover:text-amber-300 transition-colors mb-4"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to All Markets</span>
        </button>

        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-slate-900 border border-slate-800 rounded-xl p-6">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <h1 className="font-serif text-3xl font-extrabold text-white">
                {market.name}
              </h1>
              <span className="text-xs font-mono px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                {market.status}
              </span>
            </div>
            <p className="text-xs text-slate-400 font-mono flex items-center gap-3">
              <span>Open: {market.open_time}</span>
              <span>•</span>
              <span>Close: {market.close_time}</span>
              <span>•</span>
              <button
                onClick={() => onNavigateChart(market.slug)}
                className="text-amber-400 hover:underline"
              >
                View Historical Panel Chart →
              </button>
            </p>
          </div>

          {/* Model & Date Controls */}
          <div className="flex flex-col sm:flex-row sm:items-center gap-3">
            <div className="flex items-center gap-1 bg-slate-950 p-1.5 rounded-lg border border-slate-800">
              <button
                onClick={() => setDateMode('today')}
                className={`px-3 py-1.5 text-xs rounded font-medium ${
                  dateMode === 'today'
                    ? 'bg-amber-500 text-slate-950 font-bold'
                    : 'text-slate-300 hover:text-white'
                }`}
              >
                Today
              </button>
              <button
                onClick={() => setDateMode('tomorrow')}
                className={`px-3 py-1.5 text-xs rounded font-medium ${
                  dateMode === 'tomorrow'
                    ? 'bg-amber-500 text-slate-950 font-bold'
                    : 'text-slate-300 hover:text-white'
                }`}
              >
                Tomorrow
              </button>
              <input
                type="date"
                value={customDate}
                onChange={(e) => {
                  setCustomDate(e.target.value);
                  setDateMode('custom');
                }}
                className="bg-slate-900 border border-slate-800 rounded px-2 py-1 text-xs text-white"
              />
            </div>

            <div className="text-right sm:border-l sm:border-slate-800 sm:pl-3">
              <div className="text-[10px] text-slate-500 font-mono uppercase">Model Version</div>
              <div className="text-xs font-mono font-bold text-amber-400">{MODEL_VERSION}</div>
              <div className="text-[11px] text-slate-400 font-mono">
                Used: <span className="text-white font-semibold">{trainingDataCount}</span> prior draws
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* AI Statistical Explanation Banner */}
      <section className="bg-gradient-to-br from-slate-900 via-slate-900/90 to-amber-950/20 border border-amber-500/30 rounded-xl p-6 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-amber-300 font-semibold text-sm">
            <Bot className="w-5 h-5 text-amber-400" />
            <span>AI Statistical Explanation Layer</span>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-amber-500/20 border border-amber-500/40 text-amber-200">
              {aiSource === 'gemini_ai' ? 'Powered by Gemini 3.8' : 'Empirical Engine'}
            </span>
          </div>
          <button
            onClick={fetchAiExplanation}
            disabled={isAiLoading}
            className="flex items-center gap-1 text-xs text-slate-400 hover:text-amber-300 font-mono transition-colors disabled:opacity-50"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isAiLoading ? 'animate-spin' : ''}`} />
            <span>Refresh Analysis</span>
          </button>
        </div>

        {isAiLoading ? (
          <div className="py-6 flex items-center justify-center gap-3 text-sm text-slate-400 font-mono">
            <div className="w-4 h-4 rounded-full border-2 border-amber-400 border-t-transparent animate-spin" />
            <span>Synthesizing mathematical metrics & pattern resonance...</span>
          </div>
        ) : (
          <div className="text-sm text-slate-300 whitespace-pre-line leading-relaxed font-sans bg-slate-950/60 p-4 rounded-lg border border-slate-800/80">
            {aiExplanation}
          </div>
        )}
      </section>

      {/* OTC (OPEN TO CLOSE) MASTER ANK & CUT DIGITS */}
      <section className="bg-slate-900 border border-amber-500/40 rounded-xl p-6 space-y-6 shadow-xl relative overflow-hidden">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-4">
          <div>
            <div className="flex items-center gap-2">
              <Flame className="w-5 h-5 text-amber-400" />
              <h2 className="font-serif text-2xl font-extrabold text-white">
                OTC (Open To Close) 4 Strong Ank
              </h2>
              <span className="text-[11px] font-mono px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/30">
                {otc.confidence_score}% Historical Coverage
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-1">
              Deterministic 4-digit statistical set synthesizing frequency momentum, Touch Ank, and Cut harmony.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-400 font-mono">Cycle Status:</span>
            <span className="text-xs font-mono font-bold px-2 py-1 rounded bg-amber-500/10 text-amber-300 border border-amber-500/20">
              {otc.cycle_status}
            </span>
          </div>
        </div>

        {/* 4 Strong OTC Digits Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          {otc.otc_digits.map((digit, idx) => {
            const cut = otc.cut_digits[digit] || '-';
            const panasForThisDigit = otc.recommended_panas_by_digit[digit] || [];

            return (
              <div
                key={digit}
                className="bg-slate-950/80 border border-slate-800 hover:border-amber-500/60 rounded-xl p-4 text-center transition-all group"
              >
                <div className="flex items-center justify-between text-[11px] font-mono text-slate-400 mb-1">
                  <span className="font-bold text-amber-400">ANK #{idx + 1}</span>
                  <span className="bg-slate-900 px-1.5 py-0.2 rounded border border-slate-800">
                    Cut: <strong className="text-slate-200">{cut}</strong>
                  </span>
                </div>

                <div className="my-2">
                  <span className="text-5xl font-mono font-black text-amber-400 group-hover:scale-105 inline-block transition-transform">
                    {digit}
                  </span>
                </div>

                {/* Recommended Panas for this OTC digit */}
                <div className="pt-2 border-t border-slate-800/80 mt-2 space-y-1">
                  <span className="text-[10px] text-slate-500 uppercase font-mono block">
                    Top Panas
                  </span>
                  <div className="flex flex-wrap items-center justify-center gap-1">
                    {panasForThisDigit.map((p) => (
                      <span
                        key={p}
                        className="text-xs font-mono font-semibold px-2 py-0.5 rounded bg-slate-900 border border-slate-800 text-slate-200"
                      >
                        {p}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Supplementary OTC Technical Metrics */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2 border-t border-slate-800/80">
          {/* Touch Digits */}
          <div className="bg-slate-950/50 border border-slate-800 rounded-lg p-3.5 space-y-1.5">
            <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-300">
              <Target className="w-3.5 h-3.5 text-amber-400" />
              <span>Touch Ank Momentum (Past 3 Draws & Neighbors)</span>
            </div>
            <div className="flex items-center gap-2">
              {otc.touch_digits.map((td) => (
                <span
                  key={td}
                  className="font-mono text-sm font-bold px-2.5 py-1 rounded bg-slate-900 border border-slate-700 text-emerald-400"
                >
                  {td}
                </span>
              ))}
            </div>
            <p className="text-[11px] text-slate-500">
              High statistical likelihood of at least one Touch Ank repeating in Open or Close panel.
            </p>
          </div>

          {/* Family / Group Jodis */}
          <div className="bg-slate-950/50 border border-slate-800 rounded-lg p-3.5 space-y-1.5">
            <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-300">
              <Layers className="w-3.5 h-3.5 text-amber-400" />
              <span>Key Family Jodis for OTC Digits</span>
            </div>
            <div className="flex flex-wrap items-center gap-1.5">
              {otc.family_jodis.map((fj) => (
                <span
                  key={fj}
                  className="font-mono text-xs font-bold px-2 py-0.5 rounded bg-amber-500/10 border border-amber-500/20 text-amber-300"
                >
                  {fj}
                </span>
              ))}
            </div>
            <p className="text-[11px] text-slate-500">
              Formed by combinations of the top OTC candidates and their corresponding Cut digits.
            </p>
          </div>
        </div>
      </section>

      {/* 1. SINGLE DIGIT TOP CANDIDATES */}
      <section className="space-y-3">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="font-serif text-xl font-bold text-white flex items-center gap-2">
              <span>Single Digit Candidates (0 - 9)</span>
            </h2>
            <p className="text-xs text-slate-400">
              Ranked by total frequency, recent 20-draw momentum, and cycle gap variance.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3">
          {singles.map((cand) => (
            <div
              key={cand.number}
              className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex flex-col justify-between hover:border-amber-500/40 transition-colors"
            >
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="w-6 h-6 rounded-full bg-slate-800 text-slate-300 text-xs font-mono font-bold flex items-center justify-center">
                    #{cand.rank}
                  </span>
                  <span className="text-xs font-mono font-semibold text-amber-400">
                    {cand.model_score} pts
                  </span>
                </div>
                <div className="text-center py-2">
                  <span className="font-mono text-4xl font-extrabold text-white">
                    {cand.number}
                  </span>
                </div>
              </div>

              <div className="text-[11px] text-slate-400 space-y-1 font-mono pt-3 border-t border-slate-800/80 mt-2">
                <div className="flex justify-between">
                  <span>Historical Freq:</span>
                  <span className="text-slate-200">{cand.historical_frequency}</span>
                </div>
                <div className="flex justify-between">
                  <span>Recent Momentum:</span>
                  <span className="text-emerald-400">{cand.recent_frequency} hits</span>
                </div>
                <div className="flex justify-between">
                  <span>Current Gap:</span>
                  <span className="text-amber-300">{cand.current_gap} draws</span>
                </div>
                <div className="flex justify-between">
                  <span>Average Gap:</span>
                  <span className="text-slate-300">{cand.avg_gap}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* 2. JODI TOP CANDIDATES */}
      <section className="space-y-3">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="font-serif text-xl font-bold text-white">
              Jodi Candidates (00 - 99)
            </h2>
            <p className="text-xs text-slate-400">
              Joint open-close probability distribution and historical 2-digit combinations.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
          {jodis.map((cand) => (
            <div
              key={cand.number}
              className="bg-slate-900 border border-slate-800 rounded-xl p-4 hover:border-emerald-500/40 transition-colors"
            >
              <div className="flex items-center justify-between mb-1">
                <span className="text-xs font-mono text-slate-400 font-bold">
                  Rank #{cand.rank}
                </span>
                <span className="text-xs font-mono text-emerald-400 font-semibold">
                  {cand.model_score} pts
                </span>
              </div>
              <div className="text-center py-2">
                <span className="font-mono text-3xl font-extrabold text-white tracking-wider">
                  {cand.number}
                </span>
              </div>
              <div className="text-[11px] text-slate-400 space-y-1 font-mono pt-2 border-t border-slate-800/80">
                <div className="flex justify-between">
                  <span>Occurrences:</span>
                  <span className="text-slate-200">{cand.historical_frequency}</span>
                </div>
                <div className="flex justify-between">
                  <span>Current Gap:</span>
                  <span className="text-amber-300">{cand.current_gap} draws</span>
                </div>
                <div className="flex justify-between">
                  <span>Avg Cycle:</span>
                  <span className="text-slate-300">{cand.avg_gap}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* 3. PANA / PANEL TOP CANDIDATES */}
      <section className="space-y-3">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div>
            <h2 className="font-serif text-xl font-bold text-white">
              Pana / Panel Candidates (220 Panas)
            </h2>
            <p className="text-xs text-slate-400">
              Classified by Single Patti (SP), Double Patti (DP), digit sum parity, and historical recurrence.
            </p>
          </div>

          {/* Top 5, 10, 20 selector */}
          <div className="flex items-center gap-1 bg-slate-900 border border-slate-800 p-1 rounded-lg self-start">
            <span className="text-[11px] text-slate-400 px-2 font-mono">Show:</span>
            {[5, 10, 20].map((num) => (
              <button
                key={num}
                onClick={() => setPanaFilterCount(num as any)}
                className={`px-2.5 py-1 text-xs font-mono rounded ${
                  panaFilterCount === num
                    ? 'bg-amber-500 text-slate-950 font-bold'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                Top {num}
              </button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
          {displayedPanas.map((cand) => (
            <div
              key={cand.number}
              className="bg-slate-900 border border-slate-800 rounded-xl p-4 hover:border-amber-500/40 transition-colors"
            >
              <div className="flex items-center justify-between mb-1">
                <span className="text-[11px] font-mono text-slate-400 font-bold">
                  #{cand.rank}
                </span>
                <span className="text-[10px] font-mono px-1.5 py-0.2 rounded bg-amber-500/20 text-amber-300 border border-amber-500/30">
                  {cand.pana_type}
                </span>
              </div>
              <div className="text-center py-2">
                <span className="font-mono text-2xl font-bold text-white tracking-widest">
                  {cand.number}
                </span>
              </div>
              <div className="text-[11px] text-slate-400 space-y-1 font-mono pt-2 border-t border-slate-800/80">
                <div className="flex justify-between">
                  <span>Model Score:</span>
                  <span className="text-amber-400 font-bold">{cand.model_score}</span>
                </div>
                <div className="flex justify-between">
                  <span>Appearances:</span>
                  <span className="text-slate-200">{cand.historical_frequency}</span>
                </div>
                <div className="flex justify-between">
                  <span>Current Gap:</span>
                  <span className="text-amber-300">{cand.current_gap}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Mandatory Disclaimer */}
      <div className="bg-slate-900/90 border border-amber-500/30 rounded-xl p-5 text-xs text-slate-300 flex items-start gap-3">
        <ShieldAlert className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="font-semibold text-amber-300">
            DISCLAIMER: Empirical Historical Statistical Analysis
          </p>
          <p className="text-slate-400 leading-relaxed">
            These are statistical model outputs based on historical data. They are not guaranteed future results.
            Bharat Matka AI Analytics calculates mathematical probability distributions strictly for educational,
            analytical, and pattern recognition research. Never treat past frequency as guaranteed certainty.
          </p>
        </div>
      </div>
    </div>
  );
};
